## Lecture 3 - Programming Activity

### Activity 1 - Write a function that takes a filename as input.

You will be using the **bill_of_rights.txt** located in the **data** folder for this activity. Write a function that takes the filename as input and finds the total number of lines, words and most frequent word in the file and writes these statistics into a file named **‘stats.txt’**.

In [7]:
## Start Code
import numpy as np

filename= 'data/bill_of_rights.txt'
outputfile = 'data/bill_of_rights_stats.txt'

def data_statistics(filename,outputFile):
    with open(filename, "r")as f:
        countlines = f.readlines()

    with open(filename, "r")as f:
        countWords = f.read()
        countWords = countWords.split()
        most_common_word = max(set(countWords), key=countWords.count)
        print("Most common word in the file: ", most_common_word)
        print("Number of lines in the file: ", len(countlines))
        print("Number of words in the file: ", len(countWords))
    with open(outputFile, "w") as f:
        f.write("Most common word in the file: " + most_common_word + "\n")
        f.write("Number of lines in the file: " + str(len(countlines)) + "\n")
        f.write("Number of words in the file: " + str(len(countWords)) + "\n")
    
infile= 'data/bill_of_rights.txt'
outfile = 'data/bill_of_rights_stats.txt'

data_statistics(infile, outfile)

## End Code

Most common word in the file:  the
Number of lines in the file:  54
Number of words in the file:  498


### Activity 2 - Parse a file to produce a list

You will be using the file **gps.csv** located in the **data** folder for this activity. Parse the file and produce a list of coordinates (**lat** and **lon**) along with the **unix timestamp** of their visit.

In [8]:
## Start Code



## End Code

### Activity 3

1. Create an array of 5 values between 5 to 10 and remove 1,2,4 index value from the array. 
2. Create an empty array having 10 values and assign half values as 10 and half of them as 20.
3. Write a function that takes as input a 2-D ndarray and scale the last row and column by 2.5.

In [9]:
# Start Code
import numpy as np
store = np.linspace(5, 10, 5)
print(store)
store = np.delete(store, [1,2,4])  # Remove the element at index 0
print(store)

tens = np.empty((10))
tens[0:4] = 10
tens[5:10] = 20
tens

def scale_lastRow_2Darray(array, scale):
    array_copy = array.copy()  # Create a copy of the array to avoid modifying the original
    array_copy[-1] *= scale
    return array_copy

# Create a 2D array with float data type
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
scalefix = 2.5
scaled_array = scale_lastRow_2Darray(array, scalefix)
print("Original array:")    
print(array)
print("Scaled array:")
print(scaled_array)

# End Code

[ 5.    6.25  7.5   8.75 10.  ]
[5.   8.75]
Original array:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Scaled array:
[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [17.5 20.  22.5]]


### Activity 4

1. Write a function that takes a matrix as input and subtract the mean of each row of a matrix. 
2. Write a function to find the most frequent value in an array.
3. Write a function which creates an  n×n  array with  (i,j) entry equal to  i+j.


In [10]:
# Start Code

def mean_row_matrix(matrix):
    return np.mean(matrix, axis=1)

# Create a 2D array with float data type        
matrix = np.array([[1.0, 2.0, 3.0], [4.0, 1.0, 8.0], [8.0, 8.0, 1.0]], dtype=float)
mean_row = mean_row_matrix(matrix)
print("Original array:")
print(matrix)
print("Mean of each row:")
print(mean_row)

def most_common_value(matrix):
    unique, counts = np.unique(matrix, return_counts=True)
    most_common = unique[np.argmax(counts)]
    return most_common

frequent_value = most_common_value(matrix)
print("Most common value in the array:")
print(frequent_value)

# Write a function which creates an  n×n  array with  (i,j) entry equal to  i+j.
def create_matrix(n):
    return np.fromfunction(lambda i, j: i + j, (n,n), dtype=int)

matrixe = create_matrix(4)
print("Matrix with (i,j) entry equal to i+j:")
print(matrixe)
#End Code

Original array:
[[1. 2. 3.]
 [4. 1. 8.]
 [8. 8. 1.]]
Mean of each row:
[2.         4.33333333 5.66666667]
Most common value in the array:
1.0
Matrix with (i,j) entry equal to i+j:
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


### Activity 5

Using the ‘titanic_data_sample' using pandas.

1. Find and print top 5 and bottom 5 rows from the data.
2. Find the descriptive statistics of age and fare of all passengers.
3. Extract passengers who age is below 25 and have survived.
4. Extract the number of Female Passengers over 25 and in 1st class.

In [22]:
# Start Code

import csv
input_file = open("data/titanic_data_sample.csv", 'r')
reader = csv.reader(input_file)
reader = list(reader)
# Read the first 5 lines of the file
print(reader[0:5])
# Read the last 5 lines of the file
print(reader[-5:])
input_file.close()

#Extract passengers who age is below 25 and have survived.
young_survivors = [row for row in reader[1:] if row[5].isdigit() and int(row[5]) < 25 and int(row[1]) == 1]
print("Young survivors:")
print(young_survivors)

#Extract the number of Female Passengers over 25 and in 1st class.
female_passengers = [row for row in reader[1:] if row[5].isdigit() and int(row[5]) > 25 and int(row[2]) == 1 and row[4] =="female"] 
print("survivors over 25 in 1st class: femal" )
print(female_passengers)
print("Number")  
print(len(female_passengers))

#Find the descriptive statistics of age and fare of all passengers
ages = [float(row[5]) for row in reader[1:] if row[5].isdigit()]
fares = [float(row[6]) for row in reader[1:] if row[6].isdigit()]
print("Ages of all passengers:")
print(ages)
print("Fares of all passengers:")
print(fares)
print("Mean age of all passengers:")
print(np.mean(ages))
print("Mean fare of all passengers:")
print(np.mean(fares))
print("Median age of all passengers:")
print(np.median(ages))
print("Median fare of all passengers:")
print(np.median(fares))
print("Standard deviation of age of all passengers:")  
print(np.std(ages))
print("Standard deviation of fare of all passengers:")
print(np.std(fares))
# Create a new CSV file with the extracted data




# End Code

[['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'], ['1', '0', '3', 'Braund, Mr. Owen Harris', 'male', '22', '1', '0', 'A/5 21171', '7.25', '', 'S'], ['2', '1', '1', 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female', '38', '1', '0', 'PC 17599', '71.2833', 'C85', 'C'], ['3', '1', '3', 'Heikkinen, Miss. Laina', 'female', '26', '0', '0', 'STON/O2. 3101282', '7.925', '', 'S'], ['4', '1', '1', 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', '35', '1', '0', '113803', '53.1', 'C123', 'S']]
[['45', '1', '3', 'Devaney, Miss. Margaret Delia', 'female', '19', '0', '0', '330958', '7.8792', '', 'Q'], ['46', '0', '3', 'Rogers, Mr. William John', 'male', '', '0', '0', 'S.C./A.4. 23567', '8.05', '', 'S'], ['47', '0', '3', 'Lennon, Mr. Denis', 'male', '', '1', '0', '370371', '15.5', '', 'Q'], ['48', '1', '3', "O'Driscoll, Miss. Bridget", 'female', '', '0', '0', '14311', '7.75', '', 'Q'], ['49', '0', '3', 'Samaan,